#!/bin/bash

if [ $# -lt 2 ]; then
	echo 'Usage: fwemail tempalte-name receiver@address.com';
else
	mime_file="/home/jay-godara/bins/mimes/$1"

	if [ -f $mime_file ]; then
		sendmail -f jgodara@sarvika.com $2 < $mime_file > /dev/null
	else
		echo "Unknown template: $1"
	fi
fi
