#!/usr/bin/env python

import string
from random import *

min_char = 16
max_char = 16

allchar = string.ascii_letters + string.digits
password = "".join(choice(allchar) for x in range(randint(min_char, max_char)))

print password
