#!/usr/bin/env python

import sys
from Crypto.Cipher import AES
import base64

msg_text = str(sys.argv[1])
secret_key = str(sys.argv[2])

print 'Decrypt  : ', msg_text
print 'Using Key: ', secret_key

msg_text = msg_text.rjust(32)

cipher = AES.new(secret_key,AES.MODE_ECB)
decoded = cipher.decrypt(base64.b64decode(msg_text))

print decoded.strip()
